### ISSUE TITLE
Dealing with overlapping parts

### ISSUE THREAD

**Issue by NimaMojtahedi** [Mr-TalhaIlyas/EMPatches#2]
I was wondering how you are dealing with overlapping parts of 2 neighboring patches. As I checked the code it seems you are overwriting the overlapping parts when merging back. If the processing returns different information per batch then methods such as averaging or median might be a better solution.

**Comment by Mr-TalhaIlyas** [comment]
@NimaMojtahedi  yeah I know, definitely doing taking average or median would be much be better. I will add that in next version. For now maybe just setting `overlap` to 0 might help  with your use case.

**Comment by Mr-TalhaIlyas** [comment]
hi there i added various modes of merging patches in the `0.2.0` version. refer to [link](https://pypi.org/project/empatches/#description). I hope its resolved.
