### ISSUE TITLE
Generalisation of the package 

### ISSUE THREAD

**Issue by kabbas570** [Mr-TalhaIlyas/EMPatches#3]
Hi @Mr-TalhaIlyas its a great library created by you, I was thinking it would be great if you could make it more generalised to deal with the batch size and some other options to use it with [Batch_size, Channel, height, width] or [Batch_size, height, width, Channel] to make it compatible with both pytorch and TensorFlow. Thank you.

**Comment by Mr-TalhaIlyas** [comment]
thanks for suggestion, in the `0.2.0` version i added these functionalities,  refer to [link](https://pypi.org/project/empatches/#description). I hope its resolved.
