### ISSUE TITLE
Extract patches from an image by passing the indices

### ISSUE THREAD

**Issue by antonyvam** [Mr-TalhaIlyas/EMPatches#4]
Thank you for the nice library. Perhaps it might be useful to expand a bit the method to allow for someone to pass the indices as an input, something like this:

	def extract_patches(self, img, patchsize, overlap, **indices=None**):
        '''
        Parameters
        ----------
        img : image to extract patches from in [H W Ch] format.
        patchsize :  size of patch to extract from image only square patches can be
                     extracted for now.
        overlap : overlap between patched in percentage a float between [0, 1].
    
        Returns
        -------
        img_patches : a list containing extracted patches of images.
        indices : a list containing indices of patches in order, whihc can be used 
                  at later stage for 'merging_patches'.
    
        '''
        
        maxWindowSize = patchsize
        overlapPercent = overlap
        
        height = img.shape[0]
        width = img.shape[1]
        
        windowSizeX = maxWindowSize
        windowSizeY = maxWindowSize
        # If the input data is smaller than the specified window size,
        # clip the window size to the input size on both dimensions
        windowSizeX = min(windowSizeX, width)
        windowSizeY = min(windowSizeY, height)
        
        # Compute the window overlap and step size
        windowOverlapX = int(math.floor(windowSizeX * overlapPercent))
        windowOverlapY = int(math.floor(windowSizeY * overlapPercent))
        
        stepSizeX = windowSizeX - windowOverlapX
        stepSizeY = windowSizeY - windowOverlapY
        
        # Determine how many windows we will need in order to cover the input data
        lastX = width - windowSizeX
        lastY = height - windowSizeY
        xOffsets = list(range(0, lastX+1, stepSizeX))
        yOffsets = list(range(0, lastY+1, stepSizeY))
        
        # Unless the input data dimensions are exact multiples of the step size,
        # we will need one additional row and column of windows to get 100% coverage
        if len(xOffsets) == 0 or xOffsets[-1] != lastX:
        	xOffsets.append(lastX)
        if len(yOffsets) == 0 or yOffsets[-1] != lastY:
        	yOffsets.append(lastY)
        
        img_patches = []
        
		**if indices is not None:**
			indices = []
			
			for xOffset in xOffsets:
				for yOffset in yOffsets:
				  if len(img.shape) == 3:
					  img_patches.append(img[(slice(yOffset, yOffset+windowSizeY, None),
											  slice(xOffset, xOffset+windowSizeX, None))])
				  else:
					  img_patches.append(img[(slice(yOffset, yOffset+windowSizeY),
											  slice(xOffset, xOffset+windowSizeX))])
					  
				  indices.append((yOffset, yOffset+windowSizeY, xOffset, xOffset+windowSizeX))
				  
		**else:
		
			for xOffset in indices[2]:
				for yOffset in indices[0]:

				  if len(img.shape) == 3:
					  img_patches.append(img[(slice(yOffset, yOffset+windowSizeY, None),
											  slice(xOffset, xOffset+windowSizeX, None))])
				  else:
					  img_patches.append(img[(slice(yOffset, yOffset+windowSizeY),
											  slice(xOffset, xOffset+windowSizeX))])**

        
        return img_patches, indices

**Comment by Mr-TalhaIlyas** [comment]
it can be now done please update to `0.2.0` version and  refer to [link](https://pypi.org/project/empatches/#description) for usage. But in this case merging is not supported as provided indices can extract patches randomly. I hope its resolved.
