### ISSUE TITLE
Bug with overlap None

### ISSUE THREAD

**Issue by antonyvam** [Mr-TalhaIlyas/EMPatches#7]
I think there is an error with overlap when it is set to 'None'.
It should not be the following (which leads to actually maximum possible overlap so the complete opposite):
stepSizeX = 1
stepSizeY = 1
but this:
stepSizeX = patchsize
stepSizeY = patchsize
The if statement can also be removed completely and set the default value to 0 instead of None; the code then should work fine with as windowOverlapX and windowOverlapY will be set to 0.

**Comment by Mr-TalhaIlyas** [comment]
fixed in 0.2.2 version
